import Head from 'next/head';
import Image from 'next/image'
import { Inter } from 'next/font/google'
import { Button, Grid, Stack } from '@mui/material';


const inter = Inter({ subsets: ['latin'] })

export default function Home() {
  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
        <Grid
          container
          height="100vh"
          alignItems="center"
          justifyContent="center"
          direction="column"
        >
          <h1>Using Material UI with Next.js 13</h1>
          <Stack direction="row" columnGap={1}>
            <Button variant="text">Text</Button>
            <Button className="" variant="contained">
              Contained
            </Button>
            <Button className='text-black' variant="outlined">Outlined</Button>
          </Stack>
        </Grid>
    </>
  );
}
